### PR TITLE
Increment build number

### PR DESCRIPTION
**Pull request by yjh-styx**

### CODE REVIEW

**Comment by VictorVG** [comment]
Patch missing VERSION_INFO code:
```
--- "b ./src/NetBox/NetBox.rc" Git e0fec917f
+++ "a .src/NetBox/NetBox.rc" working copy
@@ -1,6 +1,6 @@
 1 VERSIONINFO
-FILEVERSION 2,4,5,535
-PRODUCTVERSION 2,4,5,535
+FILEVERSION 2,4,5,536
+PRODUCTVERSION 2,4,5,536
 FILEOS 0x4
 FILETYPE 0x2
 {
@@ -10,13 +10,13 @@ 
FILETYPE 0x2
         {
             VALUE "CompanyName", "Michael Lukashov\0"
             VALUE "FileDescription", "NetBox: SFTP/FTP/FTPS/SCP/WebDAV client for Far Manager\0"
-            VALUE "FileVersion", "2.4.5.535\0"
+            VALUE "FileVersion", "2.4.5.536\0"
             VALUE "InternalName", "FarNetBox\0"
             VALUE "LegalCopyright", "(c) 2011, 2017 Michael Lukashov\0"
             VALUE "LegalTrademarks", "\0"
             VALUE "OriginalFilename", "NetBox.dll\0"
             VALUE "ProductName", "NetBox\0"
-            VALUE "ProductVersion", "2.4.5.535\0"
+            VALUE "ProductVersion", "2.4.5.536\0"
             VALUE "ReleaseType", "stable\0"
             VALUE "WWW", "https://github.com/FarGroup/Far-NetBox\0"
         }

--- "b ./src/NetBox/resource.h" Git e0fec917f
+++ "a ./src/NetBox/resource.h" working copy
@@ -1,6 +1,6 @@
 #pragma once

-#define PLUGIN_VERSION_NUM 2,4,5,535
+#define PLUGIN_VERSION_NUM 2,4,5,536
 #define PLUGIN_VERSION_TXT "2.4.5"
 #define PLUGIN_VERSION_WTXT L"2.4.5"
```

**Comment by VictorVG** [comment]
**FIXED** https://github.com/yjh-styx/Far-NetBox/commit/2dd687a17340bcee3bab245faf2c17950a0c670c

**DrKnS**, **skipik** - спасибо!

**Comment by VictorVG** [comment]
Also needed increment build number in to ./src/NetBox/plugin_version.hpp :: 10 : Today is have:

`#define NETBOX_VERSION_BUILD         536`

 needed:

`#define NETBOX_VERSION_BUILD         537`

then all operation's is success. :)

**Comment by michaellukashov** [comment]
not actual

**Pull request closed without merging**
